package com.dataprocessor.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseConfig {

    private static final String DB_URL = "jdbc:h2:mem:dataprocessor;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private static final String DB_USER = "sa";
    private static final String DB_PASS = "";

    static {
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException e) {
            System.err.println("H2 Driver not found in classpath: " + e.getMessage());
        }
    }

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(DB_URL, DB_USER, DB_PASS);
    }

    public static void initDatabase() {
        try (Connection conn = getConnection();
             Statement stmt = conn.createStatement()) {

            // Raw event logs
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS raw_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    source_client VARCHAR(255),
                    raw_payload TEXT,
                    status VARCHAR(50),
                    error_reason TEXT,
                    received_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """);

            // Normalized canonical events with unique fingerprint constraint
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS canonical_events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    raw_event_id BIGINT,
                    client_id VARCHAR(255) NOT NULL,
                    metric VARCHAR(255) NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
                    event_fingerprint VARCHAR(64) UNIQUE NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (raw_event_id) REFERENCES raw_events(id) ON DELETE SET NULL
                );
            """);

            // Query indexes
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_canonical_client ON canonical_events(client_id);");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_canonical_metric ON canonical_events(metric);");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_canonical_ts ON canonical_events(timestamp);");

        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize database tables", e);
        }
    }
}
